### ISSUE TITLE
Project TODO List

### ISSUE THREAD

**Issue by edward62740** [J0JIng/GasSentinel#1]
- [ ] **BSEC /AI studio test**
  - [ ] Ensure that classification F1 > 0.8 for application
  - [ ] Test feasibility of dynamic switching between scan and ULP mode
  - [x] Wrt above decide battery type/nos.

- [x] **Microcontroller program components/middleware**
  - [x] Application
    - [x] EM2 power manager implementation
    - [x] Main loop ? (test necessity of RTOS)
  - [x] Thread
    - [x] sleepy/MTD (tbd poll interval)
    - [x] CoAP/S ?
    - [x] Joiner
    - [x] RFC 6763
    - [x] child supervision
  - [x] Third party
    - [x] BSEC integration/lib files (test with c++ compiler first)

- [ ] **Software integration**
  - [ ] Test overall performance wrt prototype

- [ ] **Custom Board (Bring-up Test)**
  - [x] Program/DEBUG/PTI test
  - [x] vin range [0.9, 3.5] and UVLO test
  - [x] brown out detection
  - [x] i2c0 test (400khz)
  - [x] lfclk (ext.) test
  - [x] bme688 functional test
  - [ ] RF performance characterization
